### ISSUE TITLE
Modify the square bracket function so that arbitrary sub-blocks of the matrix can be extracted

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#10]
There are three arguments:
* `m` -- a matrix being accessed
* `i` -- the column index
* `j` -- the row index

Currently `i` and `j` can only take 1-by-1 matrices. Please modify so that they can take arbitrary matrices of indices and apply the following algorithm (or a more efficient equivalent).

* Flatten `i` and `j` by stacking columns on top of each other
* Return the sub-matrix of `m` containing the rows identified by `i` and columns identified by `j`
* The order of the rows and columns in this matrix should be consistent with the ordering provided by `i` and `j`

**Comment by guanwg** [comment]
Just wonder why making i and j be matrices although I have no problem implementing this way. Would it make more sense to consider i and j as vectors?
