### ISSUE TITLE
add_calibrate() function?

### ISSUE THREAD

**Issue by bbolker** [canmod/macpan2#106]
A higher-level function that automates some of the standard steps seen in calibration functions would be useful.  Put this in `macpan2helpers` for now so  we don't have to commit to an API yet ... ??

**Comment by bbolker** [comment]
This is in progress with `macpan2helpers::mk_calibrate()`.  There's always more to do but this could possibly be closed (since it sort of exists now, possibly well enough to lower its priority relative to other stuff)

**Comment by stevencarlislewalker** [comment]
That makes sense to me @bbolker
