### ISSUE TITLE
how to change number of time steps (etc.) on the fly?

### ISSUE THREAD

**Issue by bbolker** [canmod/macpan2#108]
`time_steps` is one of the basic components of a sim object, usually defined when initially setting up the simulator.

Is there an (easy/straightforward/documented) way to change it after the object is created, other than recreating the object?  I tried 

```r
sim$ad_fun()$env$data$time_steps <- [value]
```

but without success.  reprex:

```r
remotes::install_github("canmod/macpan2helpers")
library(macpan2helpers)  ## latest version
example("mk_calibrate")
sim$ad_fun()$env$data$time_steps <- 80
```

> Error in sim$ad_fun()$env$data$time_steps <- 80 :  invalid (NULL) left side of assignment

`names(sim$ad_fun()$env$data)` (and `str()`) shows that `$data` is a list containing `$time_steps`. I can do this:

```
dd <- sim$ad_fun()$env$data
dd$time_steps <- 80
assign("data", dd, env = sim$ad_fun()$env)
```
but that seems clunky (and maybe dangerous)

More generally, is there a spec anywhere for these objects ... ??

**Comment by stevencarlislewalker** [comment]
Sorry if I'm not remembering correctly, but from memory it should be.

```
simulator$replace$time_steps(time_steps = 80)
```

**Comment by stevencarlislewalker** [comment]
In general, at the moment, I would recommend poking around by tab completing `simulator$replace$` and `simulator$add$`.

**Comment by bbolker** [comment]
I think I may even have tried that but must have missed it (the argument doesn't need to be named, BTW)

Where is an appropriate venue to have the next conversation about the future of `macpan2helpers::mk_calibrate`?  It's basically working (thanks to your commit), but now I wonder (1) whether the API/interface should be modified before I let people know about it [do you want it to be more modular, i.e. write a series of sub-functions that perform particular bits, or integrate it with bits you've been writing in parallel?]; (2) should I start updating the Calibration vignette to use it, or is that premature?

**Comment by stevencarlislewalker** [comment]
I think as long as it is marked 'experimental' somehow it is totally fine to let people know.  Updating the vignettes also sounds totally reasonable to me, especially since it is still marked 'working draft'.  Thanks so much for your work on this stuff, I really appreciate it.
