### ISSUE TITLE
Add Matrix as an explicit dependency?

### ISSUE THREAD

**Issue by papsti** [canmod/macpan2#123]
There's a warning that comes out if one is not using a version of Matrix that is compatible with the version of TMB. Why not add Matrix as an explicit dependency to DESCRIPTION, along with specific compatible version numbers of Matrix and TMB to have this set up properly and automatically, as well as eliminate the need for the warning?

**Comment by bbolker** [comment]
This is an attempt to handle a much more subtle problem, which is that the Matrix/TMB stack can break if TMB was installed (compiled) with a different version of Matrix. It's not a specific version of Matrix *per se*, but a *compatibility* issue (e.g. if I install TMB 1.2.1 with Matrix 1.6.0 installed, then I install Matrix 1.6.1 I'll get the message. It's not that I need to re-install 1.6.0, it's that I need to **re**-install TMB with the current installed (1.6.1) version of Matrix.

TBH I'm not 100% clear what drives the incompatibility (i.e., whether some part of the Matrix API actually needs to have changed in order for there to be a problem [and hence this check is being conservative/overly cautious]). The check was added to TMB [here](https://github.com/kaskr/adcomp/commit/d076d456c1c72ed800ed3fa474623b679764d06a).

This is a persistent source of pain, so I might go over to the TMB issues list and ask Kasper Kristensen (TMB author/maintainer) for a more detailed description of the issues ... 

See also:

- https://github.com/kaskr/adcomp/issues/291
- https://glmmtmb.github.io/glmmTMB/#glmmtmbtmbmatrix-mismatches
- https://github.com/timjmiller/wham/issues/33

**Comment by papsti** [comment]
thanks @bbolker! i know the answer would be good since my suggestion felt too obvious :smile:

**Comment by stevencarlislewalker** [comment]
Closing as not a macpan issue
