### ISSUE TITLE
Ensure starter models work easily with `refactorcpp` branch

### ISSUE THREAD

**Issue by papsti** [canmod/macpan2#126]
ahead of the CANMOD workshop, to ensure participants can just take a model off the shelf and simulate it

a few things that need to be done:
- [x] either write a small method to detect whether `Compartmental()` or `Compartmental2()` should be used to read the desired model files or refactor the sample model files to use the spec compatible with `Compartmental2()`
- [x] update [Example Models article](https://canmod.github.io/macpan2/articles/example_models.html)

**Comment by stevencarlislewalker** [comment]
Except we have `mp_tmb_library` instead of `Compartmental2`
