### ISSUE TITLE
add an SIR model with vital dynamics to the model library

### ISSUE THREAD

**Issue by papsti** [canmod/macpan2#147]
as an example of how to specify one-sided flows

close this issue when `sir_demo` is renamed `sir_demog`.

**Comment by stevencarlislewalker** [comment]
do we have a TMB model with birth/death @jfree-man ?

**Comment by jfree-man** [comment]
> do we have a TMB model with birth/death @jfree-man ?

We have [sir_demo](https://github.com/canmod/macpan2/tree/4f9f7cc4745cff9a33a229b35f1922a447b6c171/inst/starter_models/sir_demo), constant birth and death rates. Is this vital dynamics?

**Comment by bbolker** [comment]
This is tiny, but it would help me if this were renamed `sir_demog` - every time I see it I think it's a "demonstration", not a "demographic" model ...

**Comment by stevencarlislewalker** [comment]
I agree @bbolker , I was also thinking the same with that name.  So let's close this when the name is changed.
