### ISSUE TITLE
stop diverging refactorcpp from main

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#148]
- [x] #150
- [x] #154
- [x] #155
- [x] #153
- [x] Do the merge, bump the version number, and make a new release

## Original Description (out-of-date -- for reference)

This is the plan, although I'm sure I've forgotten something that will make this hard.

1. withdraw/rewrite stuff based on model files as `expr_list`s, but we will do this in steps such that there are multiple alternative expr_list definitions for many of the models. The reason for this is that expr_list objects are very flexible (that's good but also bad because it leaves the user with too many technical choices for how to do things), and it is also because different models have different levels of 'natural' structure that can be represented in different ways. So we will first find all models in the library that have no structure at all and can easily be thought of as scalar quantities being used in scalar expressions. Then we will make structured versions of those models, which will be more opaque than their scalar alternatives, but will be a warm up for models that really should/must be treated as structured. Then we will do those models in that structured way. Here are the steps that I have in mind.
    * Simple unstructured models -- phases of expressions
      * Before the simulation loop: any aggregation of the state variable if necessary
      * During the simulation loop: scalar expressions to compute the flow per time from one compartment to another
      * During the simulation loop: scalar expressions to compute the change per time of each state variable so that the flows from the previous step balance
    * Simple unstructured models with a state vector -- phases of expressions
      * Before the simulation loop: any aggregation of the state variable if necessary
      * During the simulation loop: scalar expressions to compute the flow per time from one compartment to another but with indexing into the state vector for accessing scalar-valued state variables
      * During the simulation loop: abstract computation of the inflows, outflows, and state update using indexing and group_sums
    * TODO: increasingly structured versions
3. ruthlessly update vignette content
4. merge integer-matrix stuff from `refactorcpp`
5. calibration interface for simple models

**Comment by jfree-man** [comment]
@stevencarlislewalker does this look right for the basic SIR model?

```
expr_list = ExprList(
  before = list(N ~ sum(S, I, R)),
  during = list(
    infection ~ S * I * beta / N,
    recovered ~ gamma * I,
    S ~ S - infection,
    I ~ I + infection - recovered,
    R ~ R + recovered
    
  )
)
```

**Comment by stevencarlislewalker** [comment]
That's it exactly @jfree-man

**Comment by bbolker** [comment]
A couple of thoughts/TODOs here:

* we need to reconcile the new/old 'quickstart' vignettes somehow (i.e. the one here has diverged a lot from the one on the main branch, should be moved/copied to something like 'structured' ?)
* I feel like the material [here](https://github.com/canmod/macpan2/blob/refactorcpp/inst/starter_models/sir/example.R) ("example.R" in the sir starter-model dir) should probably be much of the body of the quick-start vignette? At least, these details deserve to be explained somewhere ...

**Comment by stevencarlislewalker** [comment]
FYI @bbolker, @papsti -- I've fleshed out the plan to get `refactorcpp` into `main`.  Still not perfectly detailed but I think any more would be diminishing returns.

**Comment by papsti** [comment]
looks good to me at a glance!

**Comment by stevencarlislewalker** [comment]
Moving #151 out of this ticket.  Will pick it up again after merging.
