### ISSUE TITLE
Rewrite 'enough' unstructured models in `inst/starter_models` so that they work

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#150]
- [x] expression lists and defaults
- [x] move expression lists and defaults to a `tmb.R` file in a format that can be read by `mp_tmb_library`
- [x] `R` file with an example calibration to data that are simulated from the model in `tmb.R`
- [x] Remove old model definitions -- see [this](https://github.com/canmod/macpan2/issues/150#issuecomment-1889457507) comment

**Comment by bbolker** [comment]
Can I add to this that we should clean up all the junk from previous attempts (`.json`, `.csv`, `model.R` files)? (This could probably be done with a single `for` loop in the shell, something like

```
cd inst/starter_models
for i in * do
     git rm $i/*.json
     git rm $i/*.csv
     git rm $i/model.R
done
```

**Comment by jfree-man** [comment]
> Can I add to this that we should clean up all the junk from previous attempts (`.json`, `.csv`, `model.R` files)? (This could probably be done with a single `for` loop in the shell, something like
> 
> ```
> cd inst/starter_models
> for i in * do
>      git rm $i/*.json
>      git rm $i/*.csv
>      git rm $i/model.R
> done
> ```

This was only done for the unstructured models (`macpan2::show_models()$dir`), in case I temporarily need the old model definition files to understand the structured models.
