### ISSUE TITLE
Make, modify, or edit 'enough' vignettes so that they work with the TMB engine

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#154]
- [x] [Model library vignette](https://github.com/canmod/macpan2/blob/refactorcpp/vignettes/example_models.Rmd)
- [x] [Quickstart](https://github.com/canmod/macpan2/blob/refactorcpp/vignettes/quickstart.Rmd) -- defined as the 'current' easiest way to get going, which for this ticket will be the hello world SI model in the TMB engine specification
- [x] [Time-varying parameters](https://github.com/canmod/macpan2/blob/refactorcpp/vignettes/time_varying_parameters.Rmd)
- [x] [Calibration](https://github.com/canmod/macpan2/blob/refactorcpp/vignettes/calibration.Rmd) (excluding the measles examples because it is too slow -- defer #159 until after the merge of refactor c++ back to main)
- [x] [Engine-agnostic grammar](https://github.com/canmod/macpan2/blob/refactorcpp/vignettes/engine_agnostic_grammar.Rmd) -- minimal changes to get this working in the TMB engine only. this is the vignette that we presented at BIRS
- [x] Modify all others that fail so that they do not evaluate failing chunks, and move them to an appropriate place in the pkgdown site
- [x] Make the text of the above consistent with the code edits

**Comment by stevencarlislewalker** [comment]
FYI @bbolker, in case it helps with the RBF problem we discussed today ... I've checked in minimal changes that make the time varying parameters vignette work again.

**Comment by bbolker** [comment]
thanks!

**Comment by stevencarlislewalker** [comment]
Note to self: engine-agnostic vignette is now rendering but the output is numerically incorrect.

**Comment by stevencarlislewalker** [comment]
Engine-agnostic rendering issue fixed here: d4e06b39388134a5ae2929a1c5a44e3556813fe2
