### ISSUE TITLE
Merge `refactorcpp` with `main`

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#155]
- [x] All examples run without error
- [x] Unit tests all passing
- [x] 65% test coverage (that number came out of nowhere ... was initially 70% and then I gave up on that for now)
- [x] R CMD check on GH actions with zero errors or warnings (notes are fine at the moment)

**Comment by stevencarlislewalker** [comment]
Related issue:  https://github.com/canmod/macpan2/issues/160

**Comment by stevencarlislewalker** [comment]
all unit tests passing

**Comment by bbolker** [comment]
I'm a little bit puzzled that the GH action doesn't find any issues; running `R CMD check` locally (not even `--as-cran`) gives "1 ERROR,  7 WARNINGs, 4 NOTEs" ... 
[check.txt](https://github.com/canmod/macpan2/files/13967189/check.txt)

**Comment by stevencarlislewalker** [comment]
I turned off the actions.  The tests were only passing locally for me.  Maybe I haven't pushed anything.  The final item in this ticket will be R CMD check on GH actions -- I'll clarify that now.

**Comment by stevencarlislewalker** [comment]
Turned on GH actions for the [first time in a while](https://github.com/canmod/macpan2/actions/runs/7560511113/job/20586704954)

**Comment by stevencarlislewalker** [comment]
[Current status](https://github.com/canmod/macpan2/actions/runs/7571552015/job/20619317598#step:7:488)

**Comment by stevencarlislewalker** [comment]
https://github.com/canmod/macpan2/actions/runs/7573617809/job/20626149822
