### ISSUE TITLE
COVID wastewater model to match macpan1.5 implementation

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#156]
`macpan2` implementation [here](https://github.com/canmod/macpan2/blob/main/inst/starter_models/ww/tmb.R)

- [x] initial expression list and naive defaults
- [x] hazard correction
- [x] gamma-kernel convolution for reports
- [ ] variant takeover
- [x] time-variation of `beta0`

On the [likelihood](https://github.com/canmod/macpan2/tree/likelihood) branch, update the model library specification and calibration script to use real data and reflect the changes [here](https://github.com/canmod/macpan2/blob/32e4e80c2daf9a096213dfc318935b6172fe5ca0/misc/experiments/wastewater/tmb.R). 
- [x] data prep for observed time series data (`reports` and `W`)
- [ ] can/should mobility data be included in updated calibration
- [x] relevant variable transformations
- [x] use new convolution functionality to compute reports (`mp_tmb_insert_reports`)
- [x] use explicit likelihood functionality (`mp_neg_bin`, `mp_normal`)
- [x] test hazard correction functions when all infectious states are zero
- [ ] can/should phenomenological heterogeneity be included

**Comment by stevencarlislewalker** [comment]
Related to #94

**Comment by stevencarlislewalker** [comment]
info from macpan1.5 is [here](https://github.com/phac-nml-phrsd/macpan_forecast/tree/ww/comparingToMacpan2) (note this is not available publicly)

**Comment by stevencarlislewalker** [comment]
simplest possible hazard correction example [here](https://github.com/canmod/macpan2/blob/refactorcpp/inst/starter_models/si/example.R).

**Comment by jfree-man** [comment]
Hazard correction works conditional on having at least one infectious individual at time zero, otherwise S.E flow is NaN.

**Comment by stevencarlislewalker** [comment]
> Hazard correction works conditional on having at least one infectious individual at time zero, otherwise S.E flow is NaN.

Thanks @jfree-man.  I think this is a minimal example.
```
si = (mp_tmb_library("starter_models", "si", package = "macpan2")
  |> mp_tmb_update(default = list(I = 0))
)
(si
  |> mp_hazard()
  |> mp_simulator(5L, "I")
  |> mp_trajectory()
)
```

I also think that this is fixed on the [likelihood](https://github.com/canmod/macpan2/tree/likelihood) branch.  Could be fixed elsewhere, but the key to the fix I think is the `proportions` function on the `cpp` side.

**Comment by jfree-man** [comment]
Default parameter values, simulated data from `macpan1.5`, and observed data for calibration are available on the `likelihood` branch [here](https://github.com/canmod/macpan2/blob/32e4e80c2daf9a096213dfc318935b6172fe5ca0/misc/experiments/wastewater/macpan1-5_comparison_info.RDS). In the future, data should be accessible from the package and shouldn't necessarily require running a data fetching script every time it's needed.

**Comment by stevencarlislewalker** [comment]
considered close enough
