### ISSUE TITLE
tricky argument match problem with .phases

### ISSUE THREAD

**Issue by bbolker** [canmod/macpan2#157]
This issue occurs on the current main branch; I don't know if it will persist past the `refactorcpp` merge. In any case:

the `$report` method of a simulator has signature `function (..., .phases = c("before", "during", "after")) `.

Because `.phases` is after `...`, no partial argument matching is done; if `.phases` is misspelled, it gets silently absorbed into `...` (and ignored), and all three phases are reported.  It may be worth throwing a warning if `".phase" %in% names(list(...))` ... ??

**Comment by bbolker** [comment]
I see that the `refactorcpp` branch changes the default to `.phases="during"`, so this will at the very least be a less common need/mistake (still possibly that a user could manually specify `.phase = c("before", "during")` and wonder why it wasn't working ...)

**Comment by stevencarlislewalker** [comment]
Thanks Ben.  Also, going forward the idea will be to use `mp_trajectory` (for during) `mp_initial` (for before) and `mp_final` (for after), although only the first of these is currently working (trivial to do the others).

**Comment by stevencarlislewalker** [comment]
this is no longer relevant with `mp_trajectory`.  when we add `mp_final` and `mp_initial` (and maybe bring back `mp_report`, but with out any option to choose the phase and just give the user all of them), this will all be completely fine.
