### ISSUE TITLE
tmb_model.Rmd crashes/dumps core/segfaults

### ISSUE THREAD

**Issue by bbolker** [canmod/macpan2#160]
I changed `groupSums` to `group_sums` in `tmb_model.Rmd` so it would run at all (otherwise we get an error that `groupSums` isn't a recognized engine function).  I don't really understand `group_sums()` very well.  Sometimes you have to `rmarkdown::render("tmb_model.Rmd")` **twice** to get it to crash ...

In this model, `from` is the indices representing {S, I} (i.e. {0, 1} , `to` representing {I, R} {1,2}.  The relevant code is:

```r
       dummy ~ assign(rates, foi, 0, params[beta] * state[I] / params[N])
      , flow ~ state[from] * rates   
      , incidence ~ group_sums(flow, to, n_states)
      , outflow ~ group_sums(flow, from, n_states)
```

Is there a length mismatch here somewhere?  As I read it I would think that `state[from]` would only be length 2 (I don't understand `assign()`, so I don't know what `rates` is, but I assume that it if were not length-2 an error would be thrown already ...

**Comment by bbolker** [comment]
The last chunk is the bad one. TBH I'm not even sure that `vignettes/tmb_model.Rmd` was ever anything but a partially completed stub?  It wasn't created until 5190cb041 2023-10-18 "vignette work for birs" ...

**Comment by stevencarlislewalker** [comment]
Thanks @bbolker.

This is the list of vignettes that I want to get in reasonable shape for the merge:  https://github.com/canmod/macpan2/issues/154

So vignette stuff is done as far as I'm concerned.

Anything that doesn't work (like the issue you point out) I'll handle with https://github.com/canmod/macpan2/issues/155

**Comment by stevencarlislewalker** [comment]
Completed with release of v1.0.0
