### ISSUE TITLE
SHIVER model in library

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#165]

**Comment by jfree-man** [comment]
To Do:
- [ ] calibration example script using new calibration functions (and find issues/bugs a long the way)
- [ ] update README to include a vaccine supply function $\phi(t)$ as an alternate parameterization to a constant $\phi$
- [ ] update tmb.R to include a second spec with $\phi(t)$
       $\phi(t)$ should be continuous, increasing with horizontal asymptote representing the max number of supply limited vaccines 
      depends on $S(t)$ and transmission terms (perhaps not the $\beta_vSI/N$ term), goes through origin (no vaccination with zero susceptibles), high per-capita rate for small values (close to 1 or exactly 1)
- [ ] add to calibration example above with vaccine supply function

**Comment by jfree-man** [comment]
Linked wrong issue in commit, linking here 245df0e

**Comment by jfree-man** [comment]
@stevencarlislewalker what criteria do we use to decide on whether to include a new `engine_function`? Do we want this list of functions to be minimal?

I did some brainstorming on ideas for this vaccine supply function, and I'm finding not having more basic engine functions is making this more challenging than I thought.

First idea, the error function, `erf <- function(x) 2 * pnorm(x * sqrt(2)) - 1`, but `pnorm` (and less important `sqrt`) are not engine functions.

Second idea, arctan, but we only have `cos` as an engine function, which I think I can work with using the appropriate phase shifts to get `sin` but then I have to think about phase shifts.

**Comment by stevencarlislewalker** [comment]
Adding engine functions is easy.  We can add all of these easily.  I'll add all these when I get some time.

**Comment by bbolker** [comment]
Probably adding on in the wrong place, but I'd like `dlnorm` (TMB [doesn't have it](https://kaskr.github.io/adcomp/group__R__style__distribution.html), apparently); Greg Forkutza and I discovered today that log-Normal priors don't play very nicely with automatic log-transformation  (at least I couldn't figure out an easy way ...)

**Comment by jfree-man** [comment]
The default model specification is parameterized by a vaccination rate function $\phi(S(t))$ instead of a constant per capita vaccination rate $phi$.
