### ISSUE TITLE
check for misnamed args '.at' and '.phase' in insert_expressions

### ISSUE THREAD

**Issue by bbolker** [canmod/macpan2#171]
related to #167 

arguments named "at" and "phase" passed to insert_expressions are probably typos for ".at" and ".phase", and produce confusing error messages.  We could easily check.

**Comment by stevencarlislewalker** [comment]
Sitting on changes that accept `.at` and `at`.  If `at` is specified it is used, even if `.at` is explicitly specified to override the default.  Not sure if this is correct.
