### ISSUE TITLE
extracting info on all saved matrices, including SEs, with names

### ISSUE THREAD

**Issue by bbolker** [canmod/macpan2#182]
`mp_tmb_coef()` is nice.  Now I/we want: a function that's like `mp_tmb_coef()`, but returns the information on all saved matrices (`mp_tmb_report()` ? `mp_tmb_sdreport()` ?)   `obj$sdreport()` gets us the information, but we're missing something like `mp_add_descr` to include metadata like matrix names ...

**Comment by stevencarlislewalker** [comment]
`mp_trajectory_sd` should do it if I understand you correctly.

**Comment by bbolker** [comment]
Thanks!  I think I read too quickly ... it might be useful to make this an `augment()` method for simulator objects ...
