### ISSUE TITLE
attempting to get a weekly-incidence example working (à la deuxième)

### ISSUE THREAD

**Issue by GregForkutza** [canmod/macpan2#186]
I added a file [MRE.txt](https://github.com/canmod/macpan2/files/14577507/MRE.txt). It is an MRE that attempts to compute and report weekly incidence, via group_sums. I am having the following issues:

1. When I run this line of code (which adds a new variable which computes the averaged over "no of days = step_length" at the end of each simulation loop:
`  mp_tmb_insert(sir_spec, 
                phase = "after",
                expressions = list(
                  wk_incidence ~ group_sums(
                    rbind_time(infection), wk, rep(0, nweek)))
  )` 
It prints the sir_spec and shows that "wk_incidence has been added:

>After the simulation loop (t = T + 1):
1: wk_incidence ~ group_sums(rbind_time(infection), wk, rep(0, nweek))

Then when i run the next line to build the simulator environment with the sir_spec:
`simulator <- mp_simulator(
  sir_spec,
  time_steps = time_steps,
  outputs = c("S", "I", "R", "infection", "beta", "wk_incidence")
  )`
  
it throws the following warning

> In addition: Warning message:
In self$tmb_model(time_steps, outputs, default, initialize_ad_fun) :
  The following outputs were requested but not available in the model:
wk_incidence, 
They will be silently ignored.
  
Furthermore when you print the sir_spec object or the simulator object, neither show "wk_incidence" in the after-simulation loop environment.

Just to double check, when I try to calibrate the simulator anyway, it throws an error of a kind we might expect:

>Error in finalizer(x) : 
The expression given by:
    -sum(dnorm(I_obs, wk_incidence, I_sd))
contained the following symbols representing model variables:
    wk_incidence
that were neither functions nor one of the following valid variables:
    I_obs I_sd

**Comment by stevencarlislewalker** [comment]
Thanks and sorry.  The first issue is easy.  You need to assign the updated spec to a variable.  This is a [breaking change](https://canmod.github.io/macpan2/news/index.html#breaking-changes-1-3-0) that I made because I'm trying to reduce in-place modifications.  This fixed code does not give the warning.
```
  sir_spec = mp_tmb_insert(sir_spec, 
                at = Inf,
                integers = list(wk = wk),
                phase = "during",
                default = list(
                  nweek = nweek
                )
  )
  
  sir_spec = mp_tmb_insert(sir_spec, 
                phase = "after",
                expressions = list(
                  wk_incidence ~ group_sums(
                    rbind_time(infection), wk, rep(0, nweek)))
  )
```


Working on what comes later now

**Comment by stevencarlislewalker** [comment]
I'm starting to think that you did not expect the rest of the script to work if the specs were getting properly updated.  Is that correct @GregForkutza ?

**Comment by GregForkutza** [comment]
I expected the rest of the script to work but I made the changes to my actual code base (with parameter estimation) and the model calibrates successfully now. Im not sure why the MRE is not working but I don't think its important now?

However what is the best (easiest?) way to access the simulation results for what is computed as an expression in 
.phases = "after"?

Currently I can access it with the following:

` pp <- simulator$ad_fun()$env$last.par.best`
`I_hat <- simulator$report(pp, .phases = "after") %>%
        filter(matrix == "wk_incidence") %>%
        pull(value)`

Is there a built in function like `mp_trajectory()` ?

**Comment by stevencarlislewalker** [comment]
OK I think I see now.  The script has part-way implemented accumulated incidence.  If you make the following change it runs without error for me.

```
sir_spec = mp_tmb_insert(sir_spec, 
                phase = "after",
                expressions = list(
                  #wk_incidence ~ group_sums(rbind_time(infection), wk, rep(0, nweek))
                  wk_incidence ~ rbind_time(infection)
                )
  )
  
```

Sounds like you may already know that.

To answer your question, `mp_final` will be that function.  I will add it now.  All that this function will do is what you did above.

**Comment by bbolker** [comment]
If I compute `wk_inc_obs <- tapply(incidence, wk, sum)` and change the definition of `I_obs` to

```r
simulator$add$matrices(I_obs = wk_inc_obs, log_lik = empty_matrix)
```

then this all works for me.

**Comment by GregForkutza** [comment]
Thanks Ben, I was just on the tip of implementing that change. It took me the last 30mins to figure that out. I was comparing non accumulated incidence with accumulated fitted incidence.

**Comment by stevencarlislewalker** [comment]
Closing now, but feel free to re-open if I've missed something.
