### ISSUE TITLE
Remove Rcpp from LinkingTo field of DESCRIPTION

### ISSUE THREAD

**Issue by jaganmn** [canmod/macpan2#211]
You do not use headers provided by **Rcpp**, not even recursively, so you don't need it.  **Rcpp** will remain a second-order dependency via **RcppEigen**, but the C++ compiler command line will no longer contain a superfluous `-I[....]/Rcpp/include` flag.

**Comment by stevencarlislewalker** [comment]
Thank you!

**Comment by stevencarlislewalker** [comment]
fixed with [e780f91](https://github.com/canmod/macpan2/commit/e780f914123928ac74ac1ed75fa666a6437a1e9e)
