### ISSUE TITLE
More informative error message when missing `abs_rate` in `mp_per_capita_flow`

### ISSUE THREAD

**Issue by jfree-man** [canmod/macpan2#217]
The current error message when using a string expression for `rate` doesn't make it obvious that `abs_rate` wasn't specified. (On the `likelihood` branch.)

Here is a minimal example:
```
(mp_tmb_library("starter_models", "si", package = "macpan2")  
  |> mp_tmb_update(
    phase = "before"
    , at = 1
    , expressions = list(mp_per_capita_flow("S", "I", "beta * I * (S/N)^zeta"))
    , default = list(zeta = 1))
)
```

**Comment by stevencarlislewalker** [comment]
Looks like the issue can be handled [here](https://github.com/canmod/macpan2/blob/9adba35267a1293fb9ff1291d0277a9a4875adbc/R/formula_list_generators.R#L13).

Probably just need to check if `abs_rate` is null and give a useful message.  Do you mind doing that @jfree-man?
