### ISSUE TITLE
Quickstart guide -- draft descriptive text

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#28]

**Comment by stevencarlislewalker** [comment]
From my perspective this ticket is completed.  Do you agree @papsti?

**Comment by papsti** [comment]
i haven't gotten to the second part of the quickstart vignette (simulation/plotting), which is what i'm doing this morning, along with incorporating yours and ben's edits/suggestions. will close this issue with a PR once i've done a full once-over.

**Comment by stevencarlislewalker** [comment]
Excellent plan.
