### ISSUE TITLE
Convolution

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#3]
## Use-case example

```
kernel = gamma_kernel(9, 0.1, 0.25, 0.4)  ## pre-simulation loop
reports = convolution(foi * S, kernel)  ## every simulation loop
```

## Specs for convolution

convolution(m, kernel):
  * m -- matrix with saved history
  * kernel -- column vector of length less than the number of iterations

At iteration, t, do the following.

1. If t < length(kernel) return zero, otherwise continue.
2. For each element of m, get a vector with the history of this vector over each of the proceeding `length(kernel)` time times (including the current time)
3. For each element of m, take the inner product between this history vector and the kernel.
4. Return a new matrix the same shape as m but with the inner products.

**Comment by guanwg** [comment]
It seems to me that m is actually a scalar (appearing in the form of matrix). Should we make it more generic by considering m as an ordinary matrix (for example a 5-by-3 matrix)?

**Comment by stevencarlislewalker** [comment]
Good question ... thinking ...

**Comment by stevencarlislewalker** [comment]
@guanwg, please see my proposal in the edited description above.

**Comment by guanwg** [comment]
I like the new proposal and will implement it soon.

**Comment by stevencarlislewalker** [comment]
Fantastic

**Comment by guanwg** [comment]
Some details that I want to confirm with you @stevencarlislewalker ... The length of full simulation history is **time_steps**+2 (1 pre-, 1 post- and **time_steps** simulations). In doing convolution in similation _t_ (1<=_t_<=**time-step**), does the current m join the convolution calculation? If yes, then we do convolution if _t_+1>=length of kernel. Otherwise, we do convolution if _t_>= length of kernel.

**Comment by stevencarlislewalker** [comment]
Yes the current time step should be involved in the calculation.

**Comment by guanwg** [comment]
In the current design, we return either zero (a 1x1 matrix containing zero) or a convolution (_1_x_n_ matrix, where _n_ is the number of elements in m). How about we always return a matrix sized of _1_x_n_? When the history is shorter than the kernel, We use only part of the kernel. We can go one step further --- instead of flatting m, we do convolution element-wise so that the result of the convolution has the same shape as m.

**Comment by stevencarlislewalker** [comment]
> In the current design, we return either zero (a 1x1 matrix containing zero) or a convolution (_1_x_n_ matrix, where _n_ is the number of elements in m). How about we always return a matrix sized of _1_x_n_? When the history is shorter than the kernel, We use only part of the kernel. We can go one step further --- instead of flatting m, we do convolution element-wise so that the result of the convolution has the same shape as m.

I completely agree.

**Comment by guanwg** [comment]
Done! please test.

**Comment by stevencarlislewalker** [comment]
Just in the description of this ticket.

**Comment by stevencarlislewalker** [comment]
Thank you!

**Comment by guanwg** [comment]
@stevencarlislewalker I thought you agree with

**Comment by stevencarlislewalker** [comment]
Can we talk quickly?

**Comment by stevencarlislewalker** [comment]
When the history is shorter than the kernel I think that we should return zero, not use part of the kernel. But for now just using part of the kernel is OK.

I just want to confirm something.  I liked your idea that we should do this:
> instead of flatting m, we do convolution element-wise so that the result of the convolution has the same shape as m.

Is this what you implemented?

**Comment by stevencarlislewalker** [comment]
Thanks for the clarification @guanwg.  I think we should still test this implementation @Flynn-Primrose, as it is reasonable.

**Comment by stevencarlislewalker** [comment]
From @bbolker : 

> Random idea for a test of convolution (maybe for 
@Flynn-Primrose 
?) - construct two models, one with 'linear chain trick' to have an Erlang-distributed delay (e.g. SI^3R), and another than implements the force of infection as a convolution of Gamma(3) with the incidence at time t - see if they give identical (up to floating point fuzz) results. (If this is too terse and you'd like more detail please let me know.)

**Comment by stevencarlislewalker** [comment]
I understand what you are proposing @bbolker, but it would take me some time to figure out transition parameters for the `I` chain that are equivalent to the shape parameters of the Gamma.

**Comment by stevencarlislewalker** [comment]
This is tremendously helpful.  Thank you Ben.
