### ISSUE TITLE
Colon operator and sequence function

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#4]
## Sequence

* R-side symbol -- `seq`
* Three arguments
    * `from` -- first integer in the sequence
    * `length` -- length of the sequence
    * `by` -- number of integers to skip between adjacent elements in the sequence
* Example: 
    * Input: `seq(0, 4, 6)`
    * Output: `c(0, 6, 12, 18)`

## Colon

* R-side symbol -- `:`
* Two arguments
    * `from` -- first integer in the sequence
    * `to` -- last integer in the sequence
* Example:
    * Input: `5:7`
    * Output: `c(5, 6, 7)`

**Comment by stevencarlislewalker** [comment]
hooray!

**Comment by stevencarlislewalker** [comment]
Hi @Flynn-Primrose .  Please produce a test case for these colon and sequence functions.  Thanks!

**Comment by Flynn-Primrose** [comment]
@stevencarlislewalker. Done, see `sequencing_colon.R` and `sequencing_seq.R`.
