### ISSUE TITLE
calibrate + forecast vignette

### ISSUE THREAD

**Issue by bbolker** [canmod/macpan2#44]
Right now I don't think it's possible for a non-developer to figure out how to use macpan2 for calibration and forecasting. I understand that's not the focus of Irena and Mike's efforts right now (or of the upcoming workshop), but it would be good to have a short document that shows how to do this - maybe for the SIR model, for some simulated data and then for some real SIR-ish data (e.g. take an example or two from the [fitode package](https://github.com/parksw3/fitode) ?)

**Comment by stevencarlislewalker** [comment]
This is exactly what I'm doing now.

**Comment by stevencarlislewalker** [comment]
Material for vignette [here](https://github.com/canmod/macpan2/blob/main/misc/experiments/calibration/calibration.R)

**Comment by stevencarlislewalker** [comment]
[Working draft calibration vignette](https://canmod.github.io/macpan2/articles/calibration)

**Comment by stevencarlislewalker** [comment]
Outline:

- [ ] Hello world fitting problem
- [ ] Measles data
- [ ] Even easy problems are hard

**Comment by stevencarlislewalker** [comment]
We now have three separate calibration vignettes:

https://canmod.github.io/macpan2/articles/calibration
https://canmod.github.io/macpan2/articles/real_data
https://canmod.github.io/macpan2/articles/calibration_advanced
