### ISSUE TITLE
Pass through existing R-side functionality now, adding validity checks

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#48]
This doesn't need to catch everything.  The definition of done will be to make one pass through all of the R code.

**Comment by stevencarlislewalker** [comment]
## Known Validity Problems

- [ ] It is possible to specify an out-of-range row and/or column index for a matrix when specifying OptParam

**Comment by bbolker** [comment]
was that was causing @mayaearn's crash?

**Comment by stevencarlislewalker** [comment]
yes

**Comment by stevencarlislewalker** [comment]
Now if you run into @mayaearn's crash you get something more like this.

<img width="619" alt="image" src="https://github.com/canmod/macpan2/assets/2754158/bf34e0e4-9f90-479d-bcd2-9b1545a42f2a">

This could probably be made more clear, but at least the machinery is there to be as clear with wording as we want.

**Comment by stevencarlislewalker** [comment]
things have improved here so closing until we find new issues
