### ISSUE TITLE
New functions rbind_lag and rbind_time

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#5]
## Objectives

* Remove `extract_lag`, `extract_time`, `select_lag`, `select_time`
* Replace with `rbind_lag` and `rbind_time`

## Specs rbind_lag

* Arguments
    * `m` -- a matrix with saved history
    * `i` -- a column vector of integers
* Behaviour
    * For each value of `i`, access the value of the matrix, `m`, that many time steps in the past
    * If each value of `m` has the same number of columns then create a single matrix by stacking the rows on top of each other in the order provided by `i` -- and return the result
    * If not all values of `m` have the same number of columns then return an error
    * If the simulation history is not saved for the first argument, then throw an error unless the user only asks for the current matrix
    * At each iteration the vector of lags will determine a set of time-steps -- but only time-steps between 1 and `T` inclusive are valid, and all others should be thrown away

## Specs rbind_time

Same as for `rbind_lag` but now the indices in `i` refer to absolute time steps instead numbers of time-steps in the past.

## Notes to the future

We might want to extend this to `cbind_lag`, `cbind_time`, `flatten_lag`, and `flatten_time`, but for now `rbind_lag` and `rbind_time` are fine.

**Comment by guanwg** [comment]
@stevencarlislewalker Is there a good reason for i to be a matrix rather than a vector? A second question: Is "column-wise order" the same as "column-major order" 
![image](https://user-images.githubusercontent.com/13354333/206207611-4149fd76-43ec-4297-8911-8ec67b511993.png)

**Comment by stevencarlislewalker** [comment]
Yes by column-wise I meant column-major.

**Comment by guanwg** [comment]
After giving it a second thought, I believe making i a vector instead of a matrix is easier for me to handle. Can we make i a vector?

**Comment by guanwg** [comment]
excellent! thanks.

**Comment by stevencarlislewalker** [comment]
Please test only `rbind_lag` and `rbind_time` because @guanwg is waiting for testing on those before implementing `cbind_lag` and `cbind_time`.  The ticket only actually asks for `rbind_*` anyways, and we don't actually need @guanwg to make `cbind_*` because they will be so similar anyways.

**Comment by stevencarlislewalker** [comment]
I believe that `(r|c)bind_lag` should have the following additional logic:

* If it is called in the before or after phase, then an error is thrown
* Any lag requested that results in a time-index less than 1 and greater than `time_steps` should return `0`s -- that is, the pre-simulation and post-simulation time steps (`t = 0` and `t = T+1`) should not count when computing the time-lag (note that `t = 0` and `t = T+1` are valid times for `(r|c)bind_time`.

But there is a bigger problem.  What should we do about cases where the shape of the matrix changes in time?  Changing matrix shape was a reason to have lists of matrices, but we have decided to remove lists from the spec.  I still think that this is a good idea, but it does make it awkward to handle matrices of changing shape.  This is also an issue given that we currently do column binding of matrices when returning their history.  Currently this takes the last matrix as the 'reference shape' and then tries to fit other matrix sizes, resulting in garbage in some elements.

We need a rule for how to do row and column binding for matrices of changing shape.

**Comment by stevencarlislewalker** [comment]
With respect to the returning of simulation history, we should not cbind but rather return a long-form 'dataframe' with time-step, matrix-index, row-index, col-index, and value columns.

With respect to the lag functions, we should only bind the lags that are between t = 1...T.  This will result in changing shape, but that's ok given the long form return.  We should also have a count_lag function giving the number of valid time steps for doing things like moving average. As well as all_lags returning a 0 if all lags are not valid an 1 otherwise, allowing a user to pad lagged summaries and convolutions with zeros if desired even though it would be computationally inefficient.

There are deeper issues.  What if a user decides to make a parameter out of matrix element that could introduce a discontinuity?  For example the lag is given by a parameter.  Sigh

**Comment by stevencarlislewalker** [comment]
I guess for that last concern, we could do some optional assessments of the parse table to look for anything suspicious.  But we shouldn't be exhaustive -- eg checking if any matrix element below a lag or index in the parse tree is a parameter.  This sounds like symbolic algebra, which is too much for us.
