### ISSUE TITLE
Quickstart2 for a structured model

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#60]
Using `sir_vax`

**Comment by papsti** [comment]
@stevencarlislewalker, I'm getting ready to sign off for my three week vacation, so I just wanted to let you know where I stopped work on the macpan2 quickstart pt 2. 

The work for the guide is on the `ip-quickstart2-draft` branch. The guide is much more fleshed out now, though I still wouldn't call it a working draft, as the discussions of `derivations.json` and `settings.json` haven't been written yet. There also needs to be a bit of preamble at the top of the guide quickly describing the model being presented. Before this is done, the work on `bugfix-sir_vax` needs to be completed to ensure the model is defined in a way that satisfies the conventional mass-action assumption. This is discussed further in #38.

**Comment by stevencarlislewalker** [comment]
Thanks for the update @papsti.  I'm still unsure what should count as the conventional mass-action assumption, but that's OK in any case.  Have a very nice holiday!

**Comment by stevencarlislewalker** [comment]
@Flynn-Primrose may have capacity for this soon.  I'm assuming your OK with having one less thing to do @papsti , but let me know if you do plan to get back to this in the next week or so.

**Comment by papsti** [comment]
sorry, was out of office last week. i don't plan on getting back to this any time soon, so if @Flynn-Primrose wants to take a stab at the draft, i can help iterate over it later.

**Comment by stevencarlislewalker** [comment]
Thanks @papsti .  We will take you up on your offer to review.

**Comment by stevencarlislewalker** [comment]
Delivered at canmod meeting

**Comment by papsti** [comment]
was it? i suppose we had some discussion with a very basic structured model, but i guess i had envisioned a more complex but useful structured model, like age-structure where you have to track age susceptible and age infectious to calculate the forces of infection.

**Comment by stevencarlislewalker** [comment]
You are right
