### ISSUE TITLE
comments in model definition files

### ISSUE THREAD

**Issue by bbolker** [canmod/macpan2#73]
are comments allowed in (some or all) model definition files?  Could they be?  (Apparently comments are [strongly deprecated in JSON files](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json), but I think we should at least consider how models can be annotated: maybe add some optional comment/annotation elements?)

**Comment by stevencarlislewalker** [comment]
Generally not at the top of my list, but maybe they should be?

In your view, do the annotations get read into R or are they just there in the files?  The former requires more design thought than the latter.

For CSV do we want header lines?  That's reasonably simple.  For annotating rows we could just have a notes column.  For annotating columns maybe we could stuff these in the header.  

For JSON, as you point out, they 'famously' do not allow comments.  But if the comments do need to get read into R then we could have a simple file processing step before the read.

**Comment by stevencarlislewalker** [comment]
Not relevant now that model definitions are just R files.
