### ISSUE TITLE
differential equation hacks

### ISSUE THREAD

**Issue by bbolker** [canmod/macpan2#76]
@stevencarlislewalker , could you please point me to the place in the code/in a  model definition where the basic Euler-flow step is implemented, so that Kevin or I could (if we wanted) hack around with it to define  a midpoint or Runge-Kutta step instead ... ??

**Comment by stevencarlislewalker** [comment]
I wish.  I mean, here it is:  https://github.com/canmod/macpan2/blob/9bf0b9cd9b3b49cf656bccb8831cf564be6556c2/R/files_to_models.R#L522 

But I don't think this will help you much.  This section of code has not been made extensible.  Sigh.

**Comment by stevencarlislewalker** [comment]
The problem is that you need more than this step, you need to have all of the expressions that happen at each iteration encapsulated as a function. And this doesn't exist, and I'm afraid that the class structure will obscure what you need to do to do what you want. That's what I mean by 'this section of code has not been made extensible'.

**Comment by bbolker** [comment]
Hmm, will think about this (I thought we were looking at a different part of the code, where the flows were defined, but I can see that the solution might need to be implemented here, and possibly even as a separate C++ function ...)

**Comment by stevencarlislewalker** [comment]
A separate C++ function might be the answer actually, but I'd need to think it through to make sure there are no catches.

**Comment by stevencarlislewalker** [comment]
@Flynn-Primrose has made progress here while working on making per capita transmission matrices first class citizens as part of the product model work.  There exists experimental code to swap out either Euler steps or RK4 steps.  Maybe also do hazard too?

**Comment by bbolker** [comment]
Sure, if it's easy ... (we will need to be a little bit careful to be consistent about branching flows ...)

**Comment by davidearn** [comment]
> @Flynn-Primrose has made progress here while working on making per capita transmission matrices first class citizens as part of the product model work. There exists experimental code to swap out either Euler steps or RK4 steps. Maybe also do hazard too?

It would certainly be interesting to compare RK4 to Euler with hazard correction.  With care, one could presumably apply hazard corrections to the substeps in RK4 as another experiment.

**Comment by stevencarlislewalker** [comment]
Progress in this area.  Improvements Should be in the next release.

**Comment by stevencarlislewalker** [comment]
RK4 is now implemented
