### ISSUE TITLE
Objective function in c++

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#8]
- [x] Implement the spec on the C++ side (@guanwg)
- [x] Add the normal, and poisson distribution functions to the function list (@guanwg)

**Comment by guanwg** [comment]
Do you mean

**Comment by guanwg** [comment]
Can you give me the spec of "negative binomial" distribution function?

**Comment by stevencarlislewalker** [comment]
> Do you mean to calculate the return of the objective function by "Implement the spec on the C++ side"?

Yes.

> If yes, I need the following values passed from the R side:
> //DATA_IVECTOR(o_table_n)
> //DATA_IVECTOR(o_table_x)
> //DATA_IVECTOR(o_table_i)

Yes this is correct, @Flynn-Primrose  and I will work/talk through this now and get back to you.
