### ISSUE TITLE
R 3.5.0 isn't really supported

### ISSUE THREAD

**Issue by jaganmn** [canmod/macpan2#80]
`macpan2` uses the forward pipe `|>` in various places. That requires R 4.1.0, but `DESCRIPTION` has `Depends: R (>= 3.5.0)`.  At some point, one of us should check `macpan2` under a build of R 3.5.0 to see what breaks. Assuming that you really do aim to support R 3.y.z ...

**Comment by stevencarlislewalker** [comment]
Thanks for pointing this out @jaganmn.  The description file is just wrong.  We do not need to support 3.5.0, I think.  I'll make the change now.
