### ISSUE TITLE
mention starter_model in quickstart

### ISSUE THREAD

**Issue by bbolker** [canmod/macpan2#86]
from students ...

**Comment by stevencarlislewalker** [comment]
It kind of is already, in that the link in this screenshot (of quickstart) leads to an explanation of how the example models are used.

<img width="833" alt="image" src="https://github.com/canmod/macpan2/assets/2754158/08ac49f0-c5cd-4278-be56-cecad14f27f0">

**Comment by bbolker** [comment]
Sorry, I meant `model_starter()` (which isn't there because it's so new ...)

**Comment by stevencarlislewalker** [comment]
It is there, but not in an obvious place I guess.

<img width="814" alt="image" src="https://github.com/canmod/macpan2/assets/2754158/5c90dbc9-d484-4d9a-9119-6185609d586a">

**Comment by bbolker** [comment]
Hmm.  Should I back out my change, or is it OK to have this mentioned twice?

**Comment by stevencarlislewalker** [comment]
It is ok to have it mentioned twice.

**Comment by stevencarlislewalker** [comment]
Easy!  Just do it now.
