### ISSUE TITLE
Optimize simulator object size

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#89]
Example:

```
library(lobstr)
simulator = ("https://github.com"
  |> file.path("canmod/macpan2")
  |> file.path("raw/main")
  |> file.path("misc/saved-simulators/measles-model-object.rds")
  |> url('rb')
  |> readRDS()
)
obj_sizes(simulator)
(
    obj_sizes(simulator$tmb_model$expr_list$before)
  + obj_sizes(simulator$tmb_model$expr_list$during)
  + obj_sizes(simulator$tmb_model$expr_list$after)
  + obj_sizes(simulator$tmb_model$expr_list$.simulate_exprs)
  + obj_sizes(simulator$tmb_model$obj_fn$obj_fn_expr)
  + obj_sizes(simulator$tmb_model$init_mats$.initial_mats)
  + obj_sizes(simulator$cache$ad_fun$.cache)
  + obj_sizes(simulator$optimization_history$.history)
)
```

The total `simulator` size is 16.47 MB!  The sum of the pieces that I can find is 10.60 MB.  Not sure where the missing 6 MBs are.

One place where we can probably save is in the `expr_list` -- there seems to be some unnecessary stuff hitching a ride in unused formula environments.

**Comment by stevencarlislewalker** [comment]
Useful function.

```
library(macpan2)
library(lobstr)
memory_report = function(simulator) {
  .trash = simulator$ad_fun() ## fill the cache if necessary
  breakdown = c(
    before_exprs = obj_sizes(simulator$tmb_model$expr_list$before),
    during_exprs = obj_sizes(simulator$tmb_model$expr_list$during),
    after_exprs = obj_sizes(simulator$tmb_model$expr_list$after),
    simulate_exprs = obj_sizes(simulator$tmb_model$expr_list$.simulate_exprs),
    obj_fn_expr = obj_sizes(simulator$tmb_model$obj_fn$obj_fn_expr),
    initial_mats = obj_sizes(simulator$tmb_model$init_mats$.initial_mats),
    ad_fun = obj_sizes(simulator$cache$ad_fun$.cache),
    opt_history = obj_sizes(simulator$optimization_history$.history)
  )
  total = obj_sizes(simulator)
  resid = total - sum(breakdown)
  nlist(breakdown, resid, total)
}
memory_report(simulator)
```

**Comment by stevencarlislewalker** [comment]
The problem is bigger than just the size of the objects, because during optimization much more memory can get used.  I would love to figure out how to stop TMB from computing Hessians, or something else like that that is likely using up lots of memory.

**Comment by bbolker** [comment]
This could be something for the [TMB users list](https://groups.google.com/g/tmb-users) ... (is it really computing Hessians?  There's a `hessian=` argument to `MakeADFun()`, but (1) it's `FALSE` by default, (2) it controls computing the Hessian *once the optimum is reached*, not an AD-enabled Hessian computation that gets done at every step ...

**Comment by stevencarlislewalker** [comment]
Thanks @bbolker .  I guess the first question for the user group would be something general like 'when the ad fun requires more memory than is available, what are the various options?' Obviously there is the option of scaling the problem down, which @Kevinozoid has tried already.  Then there is the option of using machines with more memory, which @Kevinozoid is about to try.  But are there other options?

**Comment by stevencarlislewalker** [comment]
Can now, on refactorcpp branch, do indexing using integer vectors instead of matrix<type>.  This might help keep object size down, if the problem is the memory footprint required to keep track of indices in the automatic differentiation machinery.

**Comment by stevencarlislewalker** [comment]
Jen's NFDS model with a large index-based 'matrix' did not suffer from these issues, suggesting that the problem has been addressed with the integer stuff.  Closing now, but could open again if the issues show up again.
