### ISSUE TITLE
Flow Types Vignette

### ISSUE THREAD

**Issue by stevencarlislewalker** [canmod/macpan2#91]
A placeholder is [here](https://github.com/canmod/macpan2/blob/main/vignettes/flow_types.Rmd)

**Comment by stevencarlislewalker** [comment]
FYI @bbolker -- @Flynn-Primrose and I just talked and he is going to write this vignette, which will include stuff about vital dynamics and other absolute/one-sided flows.

**Comment by Flynn-Primrose** [comment]
I consider it partially complete. There really ought to be more detail regarding the example model. I can take another pass at it if it’s a priority.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
