### ISSUE TITLE
set unused flow initial values to NA in quickstart example?

### ISSUE THREAD

**Issue by bbolker** [canmod/macpan2#92]
It seems clearer/better (to me) to set flows that are initially unused to `NA` (or `NA_real_` if we're being fussy) than to zero, e.g. [here](https://github.com/canmod/macpan2/blob/main/vignettes/quickstart.Rmd#L212) use `flow = c(foi = NA, gamma = 0.1)` rather than `flow = c(0, gamma = 0.1)`.

If no-one objects I'll make that change in the quickstart guide (I don't know if there are other places in the docs where the same idiom occurs ...)

**Comment by stevencarlislewalker** [comment]
I completely agree.  I will note that the NA approach has not been tested and so this ticket should include tests and fixes to any bugs that pop up with this new NA requirement.  I can do all this extra stuff.

**Comment by bbolker** [comment]
I only tested it as far as running Kevin and Dennis's embryonic vital-dynamics SIR model with it and seeing that nothing obviously broke.

**Comment by bbolker** [comment]
The only thing that broke (initially) was in the calibration vignette; I think when you use plain-old `NA` (which is of type 'logical') as part of a numeric vector (e.g. `flow = c(foi = NA, other = 0.1)` it gets coerced, but when you have a one-element vector as in [this line](https://github.com/canmod/macpan2/commit/475203a4e35610f01e8f6930686d52ce6a87bebf#diff-68c14bd17257eb25c48df4a45ad96c82bd676c02836eb433ba0c5bac876420fbL66) (`beta = NA`) it doesn't get coerced and throws an error "Error in valid$check(x) : mats component is not of type numeric". Changing that to `beta = NA_real_` fixes the problem, but maybe we should try a coercion step rather than erroring here?

**Comment by stevencarlislewalker** [comment]
This seems to be completed, but we need to open a [new ticket](https://github.com/canmod/macpan2/issues/97) for coercion as mentioned in @bbolker's previous comment.
